version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_demo_db
    volumes:
      - postgres-data-demo:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

volumes:
  postgres-data-demo: